import { BadgeCheck, FlaskConical, Sparkles } from "lucide-react";

export type Provenance = "verified_filing" | "seeded_demo" | "ai_generated" | null | undefined;

const STYLES = {
  verified_filing: {
    label: "Verified filing",
    title:
      "Derived from a primary source this project actually queried — an IRS Form 990 filing, an FEC record, or GovInfo BILLSTATUS.",
    className: "text-emerald-300 bg-emerald-500/10 border-emerald-500/30",
    Icon: BadgeCheck,
  },
  seeded_demo: {
    label: "Demo data",
    title:
      "Hand-authored demonstration data. Plausible in shape, but not drawn from any filing. Not evidence of anything.",
    className: "text-amber-300 bg-amber-500/10 border-amber-500/30",
    Icon: FlaskConical,
  },
  ai_generated: {
    label: "AI-generated",
    title:
      "Unverified output from a large language model. It has not been checked against a primary source and may be wrong.",
    className: "text-violet-300 bg-violet-500/10 border-violet-500/30",
    Icon: Sparkles,
  },
} as const;

/**
 * Shows where a value came from. Every figure in this app is one of three
 * things — a real filing, hand-written demo data, or LLM output — and the UI
 * used to render all three identically, with seeded rows even carrying
 * government source labels.
 */
export default function ProvenanceBadge({
  provenance,
  size = "sm",
  className = "",
}: {
  provenance: Provenance;
  size?: "sm" | "xs";
  className?: string;
}) {
  if (!provenance || !(provenance in STYLES)) return null;
  const { label, title, className: tone, Icon } = STYLES[provenance as keyof typeof STYLES];
  const scale = size === "xs" ? "text-[10px] px-1.5 py-0.5 gap-1" : "text-xs px-2 py-1 gap-1.5";

  return (
    <span
      title={title}
      className={`inline-flex items-center ${scale} font-semibold uppercase tracking-wider rounded-md border ${tone} ${className}`}
    >
      <Icon className={size === "xs" ? "w-2.5 h-2.5" : "w-3 h-3"} aria-hidden="true" />
      {label}
    </span>
  );
}

/** Longer inline caveat for panels built entirely on non-verified data. */
export function ProvenanceNotice({ provenance }: { provenance: Provenance }) {
  if (provenance === "seeded_demo") {
    return (
      <p className="text-xs text-amber-300/80 leading-relaxed">
        Built from demonstration data, not from filings. Figures here are illustrative and
        should not be cited. See{" "}
        <a href="/methodology" className="underline hover:text-amber-200">
          methodology
        </a>
        .
      </p>
    );
  }
  if (provenance === "ai_generated") {
    return (
      <p className="text-xs text-violet-300/80 leading-relaxed">
        Generated by a language model and not verified against any primary source. Treat as a
        research prompt, not a finding. See{" "}
        <a href="/methodology" className="underline hover:text-violet-200">
          methodology
        </a>
        .
      </p>
    );
  }
  return null;
}

/** Page-level banner for views built mostly on non-verified data. */
export function ProvenanceBanner({
  kinds,
  children,
}: {
  kinds: Exclude<Provenance, null | undefined>[];
  children: React.ReactNode;
}) {
  const tone = kinds.includes("seeded_demo")
    ? "border-amber-500/30 bg-amber-500/5"
    : "border-violet-500/30 bg-violet-500/5";
  return (
    <div className={`rounded-xl border ${tone} px-4 py-3 flex flex-wrap items-center gap-x-3 gap-y-2`}>
      <span className="flex gap-2">
        {kinds.map((k) => (
          <ProvenanceBadge key={k} provenance={k} size="xs" />
        ))}
      </span>
      <p className="text-xs text-muted flex-1 min-w-[16rem] leading-relaxed">{children}</p>
    </div>
  );
}
