import { Badge } from "@/components/ui";

export type Provenance = "verified_filing" | "seeded_demo" | "ai_generated" | null | undefined;

const STYLES = {
  verified_filing: {
    label: "Verified filing",
    tone: "verified" as const,
    title:
      "Derived from a primary source this project actually queried — an IRS Form 990 filing, an FEC record, or GovInfo BILLSTATUS.",
  },
  seeded_demo: {
    label: "Demo data",
    tone: "demo" as const,
    title:
      "Hand-authored demonstration data. Plausible in shape, but not drawn from any filing. Not evidence of anything.",
  },
  ai_generated: {
    label: "AI-generated",
    tone: "ai" as const,
    title:
      "Unverified output from a large language model. It has not been checked against a primary source and may be wrong.",
  },
} as const;

/**
 * Shows where a value came from. Every figure in this app is one of three
 * things — a real filing, hand-written demo data, or LLM output — and the UI
 * used to render all three identically, with seeded rows even carrying
 * government source labels.
 */
export default function ProvenanceBadge({
  provenance,
  className = "",
}: {
  provenance: Provenance;
  className?: string;
}) {
  if (!provenance || !(provenance in STYLES)) return null;
  const { label, tone, title } = STYLES[provenance as keyof typeof STYLES];
  return (
    <Badge tone={tone} title={title} className={className}>
      {label}
    </Badge>
  );
}

/** Longer inline caveat for panels built entirely on non-verified data. */
export function ProvenanceNotice({ provenance }: { provenance: Provenance }) {
  if (provenance === "seeded_demo") {
    return (
      <p className="text-xs text-muted leading-relaxed">
        Built from demonstration data, not from filings. Figures here are illustrative and should
        not be cited.{" "}
        <a href="/methodology" className="text-accent underline underline-offset-2">
          Methodology
        </a>
        .
      </p>
    );
  }
  if (provenance === "ai_generated") {
    return (
      <p className="text-xs text-muted leading-relaxed">
        Generated by a language model and not verified against any primary source. Treat as a
        research prompt, not a finding.{" "}
        <a href="/methodology" className="text-accent underline underline-offset-2">
          Methodology
        </a>
        .
      </p>
    );
  }
  return null;
}

/** Page-level banner for views built mostly on non-verified data. */
export function ProvenanceBanner({
  kinds,
  children,
}: {
  kinds: Exclude<Provenance, null | undefined>[];
  children: React.ReactNode;
}) {
  return (
    <div className="border-l-2 border-demo bg-demo-wash/60 px-4 py-3 rounded-r-sm flex flex-wrap items-baseline gap-x-3 gap-y-2">
      <span className="flex gap-1.5">
        {kinds.map((k) => (
          <ProvenanceBadge key={k} provenance={k} />
        ))}
      </span>
      <p className="text-xs text-muted flex-1 min-w-[16rem] leading-relaxed">{children}</p>
    </div>
  );
}
