import { getDb } from "@/lib/db";
import ProvenanceBadge from "@/components/ProvenanceBadge";
import { AlertTriangle } from "lucide-react";

export const dynamic = "force-dynamic";

export const metadata = {
  title: "Methodology & Data Provenance | TTIT",
  description:
    "Where every figure in this project comes from, what is verified against a primary source, and what is demonstration or AI-generated data.",
};

type Row = { provenance: string | null; c: number };

function counts(db: ReturnType<typeof getDb>, table: string): Row[] {
  try {
    return db
      .prepare(
        `SELECT provenance, COUNT(*) as c FROM ${table} GROUP BY provenance ORDER BY c DESC`
      )
      .all() as Row[];
  } catch {
    return [];
  }
}

const TABLES: { name: string; label: string; note: string }[] = [
  { name: "financials", label: "Financials", note: "IRS Form 990 filings retrieved from the ProPublica Nonprofit Explorer API." },
  { name: "legislation", label: "Legislation", note: "Bill records and action histories from GovInfo BILLSTATUS bulk data." },
  { name: "donors", label: "Donors", note: "Hand-authored demonstration rows. No donor collector has been implemented." },
  { name: "lobbying", label: "Lobbying", note: "Hand-authored. The Senate LDA collector is not implemented." },
  { name: "policy_papers", label: "Policy papers", note: "Surfaced by prompting a language model, not by crawling publisher sites." },
  { name: "influence_links", label: "Influence links", note: "Either hand-authored or asserted by a language model." },
  { name: "analysis_verdicts", label: "AI verdicts", note: "Language model output. Not reviewed against primary sources." },
];

export default function MethodologyPage() {
  const db = getDb();

  return (
    <div className="flex flex-col gap-8 max-w-4xl">
      <div>
        <h1 className="text-4xl font-extrabold tracking-tight mb-2">
          Methodology &amp; <span className="text-primary">Provenance</span>
        </h1>
        <p className="text-muted text-lg">
          What this project actually knows, and how it knows it.
        </p>
      </div>

      <div className="glass p-6 rounded-2xl border border-amber-500/30 bg-amber-500/5">
        <h2 className="text-lg font-bold text-amber-300 flex items-center gap-2 mb-3">
          <AlertTriangle className="w-5 h-5" aria-hidden="true" />
          Read this before citing anything here
        </h2>
        <div className="text-sm text-muted space-y-3 leading-relaxed">
          <p>
            This is a student research prototype, not a journalistic or legal record. A
            substantial part of the data on this site is <strong>demonstration data</strong>{" "}
            written by hand to exercise the interface, and another part is{" "}
            <strong>generated by a language model</strong> and has not been checked against any
            primary source.
          </p>
          <p>
            Nothing here establishes that any organization or person named on this site has done
            anything improper. Influence scores, &quot;capture risk&quot; ratings and AI verdicts
            are illustrative constructs, not measurements, and they should not be read as
            findings of fact.
          </p>
          <p>
            If you are named on this site and something is wrong, please open an issue on the
            project repository and it will be corrected or removed.
          </p>
        </div>
      </div>

      <div className="glass p-6 rounded-2xl">
        <h2 className="text-xl font-bold mb-4">The three provenance levels</h2>
        <div className="flex flex-col gap-4">
          <div className="flex gap-4 items-start">
            <ProvenanceBadge provenance="verified_filing" />
            <p className="text-sm text-muted flex-1">
              Retrieved from a primary source this project actually queried: IRS Form 990 filings
              via ProPublica, campaign finance records via the FEC, and bill histories via
              GovInfo. These figures can be traced back to a public filing.
            </p>
          </div>
          <div className="flex gap-4 items-start">
            <ProvenanceBadge provenance="seeded_demo" />
            <p className="text-sm text-muted flex-1">
              Written by hand in the seed scripts so the interface has something to render.
              Plausible in shape and scale, but not drawn from any filing. Earlier versions of
              this project labelled these rows with real source names such as{" "}
              <code className="text-amber-300">irs_990</code>,{" "}
              <code className="text-amber-300">opensecrets</code> and{" "}
              <code className="text-amber-300">fara</code>, which was misleading — there is no
              OpenSecrets collector in this codebase. Those labels have been removed.
            </p>
          </div>
          <div className="flex gap-4 items-start">
            <ProvenanceBadge provenance="ai_generated" />
            <p className="text-sm text-muted flex-1">
              Produced by a large language model. Policy papers were surfaced by asking a model
              what exists rather than by crawling publisher sites, so some entries may not
              correspond to a real document. Verdicts and confidence percentages are model output.
              A confidence score reflects the model&apos;s phrasing, not evidential strength.
            </p>
          </div>
        </div>
      </div>

      <div className="glass p-6 rounded-2xl">
        <h2 className="text-xl font-bold mb-4">What each table contains</h2>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-card-border text-left text-muted">
                <th scope="col" className="py-2 pr-4 font-semibold">Table</th>
                <th scope="col" className="py-2 pr-4 font-semibold">Provenance</th>
                <th scope="col" className="py-2 font-semibold">Source</th>
              </tr>
            </thead>
            <tbody>
              {TABLES.map((t) => {
                const rows = counts(db, t.name);
                return (
                  <tr key={t.name} className="border-b border-card-border/50 align-top">
                    <td className="py-3 pr-4 font-semibold text-white whitespace-nowrap">{t.label}</td>
                    <td className="py-3 pr-4">
                      <div className="flex flex-col gap-1.5">
                        {rows.length === 0 ? (
                          <span className="text-muted">empty</span>
                        ) : (
                          rows.map((r) => (
                            <span key={String(r.provenance)} className="flex items-center gap-2 whitespace-nowrap">
                              <ProvenanceBadge
                                provenance={r.provenance as never}
                                size="xs"
                              />
                              <span className="text-muted tabular-nums">
                                {r.c.toLocaleString()}
                              </span>
                            </span>
                          ))
                        )}
                      </div>
                    </td>
                    <td className="py-3 text-muted">{t.note}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>

      <div className="glass p-6 rounded-2xl">
        <h2 className="text-xl font-bold mb-4">Known limitations</h2>
        <ul className="text-sm text-muted space-y-3 list-disc pl-5 leading-relaxed">
          <li>
            <strong className="text-white">Influence &quot;strength&quot; is not a measurement.</strong>{" "}
            The values mix three incompatible things: hand-written literals, a constant assigned
            to every model-discovered link, and a donation divided by the largest donation to the
            same organization. They are averaged together and rendered as a percentage, which
            overstates their precision considerably.
          </li>
          <li>
            <strong className="text-white">A link is co-occurrence, not causation.</strong> Link
            types are causal verbs — <em>informs</em>, <em>advocates_for</em>, <em>influences</em>{" "}
            — applied to topical overlap. There is no control group and no base rate.
          </li>
          <li>
            <strong className="text-white">&quot;Capture risk&quot; is a composed heuristic.</strong>{" "}
            Its four weights were chosen by hand, not fitted or validated against anything.
          </li>
          <li>
            <strong className="text-white">Attribution.</strong> Nonprofit financial data comes
            from the{" "}
            <a href="https://projects.propublica.org/nonprofits/" className="text-primary underline">
              ProPublica Nonprofit Explorer
            </a>
            . Campaign finance data comes from the{" "}
            <a href="https://www.fec.gov/" className="text-primary underline">FEC</a>. Legislative
            data comes from{" "}
            <a href="https://www.govinfo.gov/" className="text-primary underline">GovInfo</a>.
          </li>
        </ul>
      </div>
    </div>
  );
}
